csv_reader/urls.py
from django.urls import path

from .views import answers_and_users, upload_file

app_name = "csv_reader"

urlpatterns = [
    path("", upload_file, name="index"),
    path("user_answers/", answers_and_users, name="answers"),
]

diagnostic/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("csv_reader.urls", namespace="csv_reader")),
]

csv_reader/models.py
from django.db import models

from .utils.coding import (
    answer_choices,
    children_choices,
    living_choices,
    martial_status_choices,
    sex_choices,
    work_status_choices,
    yes_no_choices,
)

# Create your models here.


class User(models.Model):
    user_id = models.IntegerField(verbose_name="ID")
    time_create = models.DateTimeField(verbose_name="Время создания")
    time_changed = models.DateTimeField(verbose_name="Время изменения")
    name = models.CharField(max_length=150, verbose_name="Фамилия, Имя, Отчество")
    group = models.CharField(max_length=50, verbose_name="Группа")
    member_gz_2021_2022 = models.CharField(
        choices=yes_no_choices,
        max_length=10,
        null=True,
        blank=True,
        verbose_name="Участник GZ 2021-2022",
    )
    sex = models.CharField(choices=sex_choices, max_length=50, verbose_name="Пол")
    age = models.CharField(max_length=30, verbose_name="Возраст")
    marital_status = models.CharField(
        choices=martial_status_choices, max_length=50, verbose_name="Семейное положение"
    )
    living = models.CharField(
        choices=living_choices, max_length=50, verbose_name="Проживаю"
    )
    children = models.CharField(
        choices=children_choices, max_length=40, verbose_name="Дети"
    )
    work_status = models.CharField(
        choices=work_status_choices, max_length=50, verbose_name="Занятость"
    )
    working_in_fishing_or_shipping = models.CharField(
        choices=yes_no_choices,
        null=True,
        max_length=30,
        verbose_name="Связана ли Ваша основная деятельность с рыбной отраслью и (или) мореходной деятельностью",
    )
    working_maritime = models.CharField(
        choices=yes_no_choices,
        null=True,
        max_length=30,
        verbose_name="морские профессии (судовождение, эксплуатация судовых энергетических установок)",
    )
    working_fishing_industry = models.CharField(
        choices=yes_no_choices,
        null=True,
        max_length=30,
        verbose_name="промышленное рыболовство",
    )
    working_fishing_technology = models.CharField(
        choices=yes_no_choices,
        max_length=30,
        null=True,
        verbose_name="технология рыбы и рыбных продуктов, морская биотехнология",
    )
    working_aquaculture = models.CharField(
        choices=yes_no_choices,
        max_length=30,
        null=True,
        verbose_name="аквакультура и рыбоводство",
    )
    working_economic = models.CharField(
        choices=yes_no_choices,
        max_length=30,
        null=True,
        verbose_name="экономика и управления морехозяйственной/рыбохозяйственной деятельностью",
    )
    working_it = models.CharField(
        choices=yes_no_choices,
        max_length=30,
        null=True,
        verbose_name="информационные технологии в морехозяйственной/рыбохозяйственной деятельности",
    )
    working_other = models.CharField(
        choices=yes_no_choices, max_length=30, null=True, verbose_name="другое"
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Question(models.Model):
    text_question = models.TextField()

    def __str__(self):
        return self.text_question


class Answers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=50, blank=True, null=True)
    answer_bin = models.CharField(
        choices=answer_choices, max_length=50, blank=True, null=True
    )

    def __str__(self):
        return self.answer

csv_reader/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()


class GetAnswersForm(forms.Form):
    field = forms.CharField()
    value = forms.CharField()

csv_reader/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from .forms import GetAnswersForm, UploadFileForm
from .utils.configure_logging import configure_logging
from .utils.crud import (
    check_questions,
    create_answers,
    create_user,
    get_info,
    select_info,
)

# Create your views here.

logger = configure_logging(__file__)


def upload_file(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if not request.FILES["file"].name.endswith("csv"):
            return render(request, "index.html", {"msg": "Invalid extension of file"})
        if form.is_valid():
            questions, users_and_answers = get_info(form)
            q_db = check_questions(questions=questions)
            for info in users_and_answers:
                try:
                    user = create_user(info=info["user"])
                    create_answers(answers=info["answers"], questions=q_db, user=user)
                except BaseException as err:
                    logger.exception(err)
            return render(request, "index.html", {"msg": "Successfully uploaded"})
    return render(request, "index.html")


def answers_and_users(request):
    if request.method == "GET":
        form = GetAnswersForm(request.GET)
        if form.is_valid():
            try:
                users = select_info(form.cleaned_data)
            except Exception as err:
                return render(
                    request, "users.html", {"msg": f"Invalid input data {err}"}
                )
            if users:
                request.session["users"] = users
            else:
                return render(request, "users.html", {"msg": "Users are not found"})
        paginator = Paginator(list(request.session.get("users").items()), 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return render(
            request,
            "users.html",
            {"page_obj": page_obj, "index": (page_obj.number - 1) * 10},
        )
    return render(request, "index.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>csv reader</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'csv_reader:index' %}">Import</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'csv_reader:answers' %}">Answers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <form method="post" enctype="multipart/form-data" class="mb-3">
        {% csrf_token %}
        <label for="id_file">File:</label>
        <input class="form-control" type="file" name="file" required id="id_file">
        <br>
        <input type="submit" class="btn btn-primary" value="Upload">
    </form>
    <br>
    {% if msg %}
    {{ msg }}
    {% endif %}
    {% endblock %}
</div>

templates/users.html
{% extends 'base.html' %}


{% block content %}
<div class="container-fluid">
    <br>
    <form action="{% url 'csv_reader:answers' %}" method="get" class="row row-cols-lg-auto g-3 align-items-center">
        {% csrf_token %}

        <div class="mb-3">
            <label for="field" class="visually-hidden">Preference</label>
            <select id="field" name="field" class="form-select" id="inlineFormSelectPref">
                <option selected>Choose...</option>
                <option value="user_id">ID</option>
                <option value="name">Фамилия, Имя, Отчество</option>
                <option value="sex">Пол</option>
                <option value="age">Возраст</option>
                <option value="marital_status">Семейное положение</option>
                <option value="children">Детность</option>
                <option value="work_status">Занятость</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="value"></label>
            <input type="text" id="value" name="value" placeholder="Enter value">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    {% if msg %}
    {{ msg }}
    {% endif %}

    {% if page_obj.object_list %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Фамилия, Имя, Отчество</th>
            <th scope="col">Результат</th>
        </tr>
        </thead>
        <tbody>
        {% for _, user in page_obj.object_list %}
        <tr>
            <th scope="row">{{ index|add:forloop.counter }}</th>
            <td>{{ user.0 }}</td>
            <td title="{{user.1}}">{{ user.1|slice:":40" }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
    {% endif %}
</div>
{% endblock %}